version: '3.4'
#SMART_TUTOR_FRONT_API_URL=http://127.0.0.1:8080/smart-tutor/api/


services:
  pharmacy-front:
      build:
        context: .
        dockerfile: Dockerfile_Pharmacy
        target: gatewayWithFront
        args:
          - SMART_TUTOR_API_URL=http://localhost:8080/api/
      restart: on-failure
      networks:
        - pharmacy-application_net
      ports:
        - "8085:8080"
      depends_on:
        - pharmacy
  # patients-front:
  #     build:
  #       context: .
  #       dockerfile: Dockerfile_Patients
  #       target: gatewayWithFront
  #       args:
  #         - SMART_TUTOR_API_URL=http://localhost:5111/api/
  #     restart: on-failure
  #     networks:
  #       - patients-application_net
  #     ports:
  #       - "8086:8080"
  #     depends_on:
  #       - patients-portal

  pharmacy:
    image: psw8org/pharmacy-back:latest
    networks:
      - pharmacy_database_net
      - pharmacy-application_net
    container_name: Pharmacy_Back
    environment:
       SERVER: "database-pharmacy"
       DB_PORT: "5432"
       DB_NAME: "Pharmacy"
       DB_USER: "postgres"
       DB_PASSWORD: "root"
    expose:
      - "80"
    ports:
      - "8080:80"
    restart: on-failure
    #extra hosts can be used for standalone SQL Server or services at the dev PC
    depends_on:
      - database-pharmacy

  patients-portal:
    image: psw8org/patients-portal-back:latest
    networks:
      - patients_database_net
      - patients-application_net
    container_name: Patients_Portal_Back
    environment:
       SERVER: "database-patients"
       DB_PORT: "5432"
       DB_NAME: "psw_database"
       DB_USER: "postgres"
       DB_PASSWORD: "wasd"
    expose:
      - "80"
    ports:
      - "5111:80"
    restart: on-failure
    #extra hosts can be used for standalone SQL Server or services at the dev PC
    depends_on:
      - database-patients

  integrations:
    image: psw8org/integration-app:latest
    networks:
      - integrations_database_net
    container_name: Integrations_Back
    environment:
       SERVER: "database-integration"
       DB_PORT: "5432"
       DB_NAME: "Integration"
       DB_USER: "postgres"
       DB_PASSWORD: "root"
    expose:
      - "80"
    ports:
      - "5112:80"
    restart: on-failure
    #extra hosts can be used for standalone SQL Server or services at the dev PC
    depends_on:
      - database-integration

  
  database-patients:
    image: postgres:13
    restart: always
    container_name: Patients_Portal_Database
    networks:
      - patients_database_net
    environment:
      POSTGRES_PASSWORD: "wasd"
      POSTGRES_USER: "postgres"
    ports:
      - "7083:5432"
  database-pharmacy:
    image: postgres:13
    restart: always
    container_name: Pharmacy_Database
    networks:
      - pharmacy_database_net
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
    ports:
      - "7081:5432"
  database-integration:
    image: postgres:13
    restart: always
    container_name: Integrations_Database
    networks:
      - integrations_database_net
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
    ports:
      - "7082:5432"

networks:
  pharmacy_database_net:
    name: pharmacy_database_net
    driver: bridge
  patients_database_net:
    name: patients_database_net
    driver: bridge
  integrations_database_net:
    name: integrations_database_net
    driver: bridge
  pharmacy-application_net:
    name: pharmacy-application_net
    driver: bridge
  patients-application_net:
    name: patients-application_net
    driver: bridge